name: Release
on:
  release:
    types: [released]
env:
  IMAGE_NAME: godotsteam-ci
jobs:
  version:
    name: Get Version
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.calculate.outputs.version }}
    steps:
      - id: calculate
        run: |
          REF_NAME=${{ github.ref_name }}
          echo "version=${REF_NAME%-*}" >> $GITHUB_OUTPUT
  build:
    name: Build Image
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-20.04
    needs: [version]
    steps:
      - uses: actions/checkout@v3
      - run:  echo IMAGE_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:${{ needs.version.outputs.version }}
            ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            GODOT_VERSION=${{ needs.version.outputs.version }}
